# config/meta.yml
 meta_product_name: "Subscriptify"
 meta_title: "Subscriptify - Deja de regalar dinero en suscripciones que no usas"
 meta_description: "La herramienta #1 para trackear gastos, recibir alertas de vencimiento y ahorrar cientos de dólares al año. Toma el control de tus finanzas hoy."
 meta_image: "White.png"
 twitter_account: "@subscriptify"
